### ISSUE TITLE
ETF validation service

### ISSUE THREAD

**Issue by fxprunayre** [INSPIRE-MIF/daobs#60]
ETF validation service is an application for validating view and download INSPIRE services. A new task in the dashboard will be set up in order to:
* search all service metadata record (eg. https://github.com/titellus/daobs/blob/daobs-1.0.x/tasks/service-dataset-indexer/src/main/resources/META-INF/spring/daobs-task-routes.xml#L147)
* get service type and service URL from the record
* send service URL to the ETF validator with the proper testsuite to run
* collect results and store them in the index

Development branch: https://github.com/josegar74/daobs/tree/etf-validation-checker/tasks/eft-validation-checker

ETF validation service download, installation instruction: 
* Download from http://www.geostandaarden.nl/validatie/inspire/versies/1.4/ETF1.4.zip - a maven task is created for easy installation
 * Document how to install
 * ETF is a local java application 

ETF validation service response is an XML and HTML report.

An extract of the validation result is stored in new index fields (and will provide more details than metadata validation currently based on the JRC validator): 
* etfValid: indicating if service is valid or not
* etfCompletnessIndicator: 
* etfValidReport: validation report (raw report is stored)
* etfValidDate: validation date
* Optional extra fields (TODO ?):
 * etfStepsX: true/false
 * etfPercOfGetMapFailure: Percentage of layers with failing GetMap requests on WMS/WMTS
 * etfPercOfGetFeatureFailure: Percentage of featureTypes with failing GetFeature requests on WFS
 * etfPercOfGetDatasetFailure: Percentage of failing GetDataset requests on Atom services

The ETF validation service will be called by the dashboard as a java application. 

* Create a dashboard for visualizing the ETF indicators : https://github.com/titellus/banana/blob/7a4de4e7502f899de3b6a60dabc935aaea258f5b/filteredResources/app/dashboards/CATALOG-ETFValidationReport.json

Demo: http://apps.titellus.net/dashboard/dashboard2/#/dashboard/solr/ETF%20Validation%20report

**Comment by pvgenuchten** [comment]
the ETF software is available here
http://www.geostandaarden.nl/validatie/inspire/versies/1.4/ETF1.4.zip

**Comment by pvgenuchten** [comment]
some questions related to the ETF testing

- We suggest to only do ETF validation on endpoints that are mentioned in iso19119 service metadata
- If multiple metadata reference the same endpoint, an ETF validation will only run once
- If multiple endpoints are mentioned in one metadata, only the first will be evaluated (if we get more then 1 result per service-metadata, we have no fields to store the result)
- How to detect if an endpoint is a WM(T)S/WFS/ATOM endpoint. In dutch profile we use the protocol=OGC:W*S, but that is not used outside Netherlands, can we still use that, or should we look for alternatives that also work outside NL?

if we can't use the protocol, an (or the only?) alternative is to resolve {endpoint}?request=getcapabilities and check what it returns... a wfs/wms/wmts/atom response.  Atom doesn't have a getcapabilities parameter, but it usually won't break if we add the parameter anyway
Slight alternative is to look in the keywords if it is a view or a download service.

**Comment by josegar74** [comment]
About this:

If multiple endpoints are mentioned in one metadata, only the first will be evaluated (if we get more then 1 result per service-metadata, we have no fields to store the result)


* Service metadata can link to several services?
* If yes, can't we store the reports for every end point in SOLR using kind of array?

**Comment by pvgenuchten** [comment]
Response Ine:

Yes please only validate the services in the service metadata. There is also the declared conformance of that service one of the metadata elements. (not in the dataset metadata). There should be only one accesspoint in the service metadata.

Use for detecting the kind of service by preference no specific Dutch metadata elements.
In INSPIRE the spatial data service type is mandatory, that can be used to divide between view and download services.
But that’s not enough, therefore the capabilities can be used, what can not respond should be an ATOM, because that’s the only not OGC service.

So:
- if multiple endpoints, take first one
- check the servicetype (either download or view)
- if download servicetype; test if {endpoint}?request=getcapabilities&version=2.0.0&service=wfs returns sensible content else try to parse response as atom.
- if view servicetype; test if {endpoint}?request=getcapabilities&version=1.0.0&service=wmts returns sensible content else try {endpoint}?request=getcapabilities&version=1.3.0&service=wms

**Comment by fxprunayre** [comment]
Closing. Version 1.5 added in #73
